/*
-- Query: SELECT * FROM mad_scientist.items
LIMIT 0, 1000

-- Date: 2022-11-26 13:42
*/
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (1,'Kalista\'s Black Spear',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3599.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (2,'Cull',245,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1083.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (3,'Dark Seal',433,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1082.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (4,'Doran\'s Blade',592,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1055.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (5,'Doran\'s Ring',513,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1056.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (6,'Doran\'s Shield',213,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1054.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (7,'Emberknife',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1035.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (8,'Guardian\'s Blade',1850,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3177.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (9,'Guardian\'s Hammer',1650,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3184.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (10,'Guardian\'s Horn',400,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2051.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (11,'Guardian\'s Orb',1488,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3112.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (12,'Hailblade',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1039.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (13,'Relic Shield',264,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3858.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (14,'Spectral Sickle',327,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3862.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (15,'Spellthief\'s Edge',451,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3850.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (16,'Steel Shoulderguards',260,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3854.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (17,'Tear of the Goddess',336,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3070.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (18,'Control Ward',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2055.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (19,'Corrupting Potion',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2033.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (20,'Elixir of Iron',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2138.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (21,'Elixir of Sorcery',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2139.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (22,'Elixir of Wrath',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2140.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (23,'Health Potion',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2003.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (24,'Refillable Potion',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2031.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (25,'Farsight Alteration',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3363.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (26,'Oracle Lens',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3364.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (27,'Stealth Ward',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3340.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (28,'Your Cut',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3400.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (29,'Commencing Stopwatch',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2419.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (30,'Eye of the Herald',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3513.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (31,'Minion Dematerializer',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2403.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (32,'Perfectly Timed Stopwatch',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2423.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (33,'Poro-Snax',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2052.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (34,'Slightly Magical Footwear',300,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2422.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (35,'Total Biscuit of Everlasting Will',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2010.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (36,'Berserker\'s Greaves',1415,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3006.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (37,'Boots',300,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1001.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (38,'Boots of Swiftness',720,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3009.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (39,'Ionian Boots of Lucidity',1073,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3158.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (40,'Mercury\'s Treads',990,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3111.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (41,'Mobility Boots',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3117.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (42,'Plated Steelcaps',940,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3047.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (43,'Sorcerer\'s Shoes',1100,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3020.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (44,'Amplifying Tome',435,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1052.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (45,'B. F. Sword',1400,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1038.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (46,'Blasting Wand',870,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1026.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (47,'Cloak of Agility',600,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1018.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (48,'Cloth Armor',300,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1029.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (49,'Dagger',300,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1042.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (50,'Faerie Charm',250,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1004.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (51,'Long Sword',350,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1036.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (52,'Needlessly Large Rod',1305,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1058.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (53,'Null-Magic Mantle',450,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1033.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (54,'Pickaxe',875,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1037.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (55,'Rejuvenation Bead',300,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1006.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (56,'Ruby Crystal',400,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1028.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (57,'Sapphire Crystal',350,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1027.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (58,'Sheen',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3057.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (59,'Stopwatch',0,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2420.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (60,'Aegis of the Legion',1407,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3105.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (61,'Aether Wisp',653,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3113.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (62,'Bami\'s Cinder',800,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6660.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (63,'Bandleglass Mirror',952,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4642.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (64,'Blighting Jewel',1250,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4630.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (65,'Bramble Vest',600,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3076.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (66,'Caulfield\'s Warhammer',1142,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3133.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (67,'Chain Vest',800,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1031.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (68,'Crystalline Bracer',833,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3801.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (69,'Executioner\'s Calling',700,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3123.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (70,'Fiendish Codex',1028,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3108.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (71,'Forbidden Idol',690,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3114.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (72,'Frostfang',888,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3851.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (73,'Giant\'s Belt',933,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1011.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (74,'Glacial Buckler',1017,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3024.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (75,'Harrowing Crescent',760,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3863.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (76,'Hearthbound Axe',900,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3051.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (77,'Hexdrinker',1505,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3155.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (78,'Hextech Alternator',944,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3145.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (79,'Ironspike Whip',1050,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6029.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (80,'Kindlegem',800,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3067.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (81,'Kircheis Shard',375,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2015.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (82,'Last Whisper',1450,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3035.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (83,'Leeching Leer',1300,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4635.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (84,'Lost Chapter',1557,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3802.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (85,'Negatron Cloak',900,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1057.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (86,'Noonquiver',1425,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6670.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (87,'Oblivion Orb',761,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3916.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (88,'Phage',1058,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3044.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (89,'Quicksilver Sash',540,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3140.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (90,'Rageknife',625,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6677.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (91,'Recurve Bow',625,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1043.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (92,'Runesteel Spaulders',627,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3855.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (93,'Seeker\'s Armguard',953,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3191.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (94,'Serrated Dirk',1616,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3134.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (95,'Spectre\'s Cowl',1117,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3211.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (96,'Targon\'s Buckler',634,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3859.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (97,'Tiamat',875,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3077.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (98,'Vampiric Scepter',900,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/1053.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (99,'Verdant Barrier',885,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4632.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (100,'Warden\'s Mail',800,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3082.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (101,'Watchful Wardstone',667,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4638.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (102,'Winged Moonplate',460,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3066.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (103,'Zeal',1050,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3086.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (104,'Abyssal Mask',2097,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/8020.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (105,'Anathema\'s Chains',2267,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/8001.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (106,'Archangel\'s Staff',2538,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3003.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (107,'Ardent Censer',2245,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3504.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (108,'Axiom Arc',3158,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6696.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (109,'Banshee\'s Veil',2817,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3102.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (110,'Black Cleaver',3308,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3071.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (111,'Black Mist Scythe',1400,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3864.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (112,'Blade of The Ruined King',2454,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3153.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (113,'Bloodthirster',3689,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3072.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (114,'Bulwark of the Mountain',1402,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3860.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (115,'Chempunk Chainsword',3258,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6609.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (116,'Chemtech Putrifier',2338,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3011.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (117,'Cosmic Drive',2807,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4629.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (118,'Dead Man\'s Plate',1760,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3742.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (119,'Death\'s Dance',3225,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6333.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (120,'Demonic Embrace',2565,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4637.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (121,'Edge of Night',3183,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3814.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (122,'Essence Reaver',2908,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3508.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (123,'Fimbulwinter',2537,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3121.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (124,'Force of Nature',2253,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4401.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (125,'Frozen Heart',2893,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3110.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (126,'Gargoyle Stoneplate',2680,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3193.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (127,'Guardian Angel',2375,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3026.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (128,'Guinsoo\'s Rageblade',1925,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3124.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (129,'Horizon Focus',2649,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4628.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (130,'Hullbreaker',3267,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3181.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (131,'Infinity Edge',3250,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3031.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (132,'Knight\'s Vow',2200,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3109.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (133,'Lich Bane',2127,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3100.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (134,'Lord Dominik\'s Regards',3100,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3036.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (135,'Manamune',2325,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3004.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (136,'Maw of Malmortius',3358,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3156.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (137,'Mejai\'s Soulstealer',702,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3041.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (138,'Mercurial Scimitar',2920,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3139.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (139,'Mikael\'s Blessing',2680,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3222.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (140,'Morellonomicon',2758,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3165.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (141,'Mortal Reminder',2609,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3033.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (142,'Muramana',2829,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3042.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (143,'Nashor\'s Tooth',3425,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3115.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (144,'Navori Quickblades',3700,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6675.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (145,'Pauldrons of Whiterock',1492,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3857.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (146,'Phantom Dancer',2209,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3046.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (147,'Rabadon\'s Deathcap',2610,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3089.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (148,'Randuin\'s Omen',2733,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3143.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (149,'Rapid Firecannon',1759,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3094.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (150,'Ravenous Hydra',3380,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3074.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (151,'Redemption',2313,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3107.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (152,'Runaan\'s Hurricane',2009,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3085.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (153,'Rylai\'s Crystal Scepter',2698,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3116.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (154,'Seraph\'s Embrace',3611,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3040.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (155,'Serpent\'s Fang',2604,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6695.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (156,'Serylda\'s Grudge',3358,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6694.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (157,'Shadowflame',2708,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4645.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (158,'Shard of True Ice',1645,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3853.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (159,'Silvermere Dawn',2920,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6035.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (160,'Spirit Visage',2667,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3065.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (161,'Staff of Flowing Water',2028,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6616.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (162,'Sterak\'s Gage',1067,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3053.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (163,'Stormrazor',2575,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3095.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (164,'The Collector',3404,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6676.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (165,'Thornmail',2133,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3075.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (166,'Titanic Hydra',2384,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3748.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (167,'Umbral Glaive',2716,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3179.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (168,'Vigilant Wardstone',800,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4643.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (169,'Void Staff',3587,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3135.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (170,'Warmog\'s Armor',3000,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3083.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (171,'Winter\'s Approach',2033,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3119.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (172,'Wit\'s End',3120,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3091.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (173,'Youmuu\'s Ghostblade',3344,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3142.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (174,'Zeke\'s Convergence',2250,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3050.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (175,'Zhonya\'s Hourglass',3040,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3157.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (176,'Crown of the Shattered Queen',3563,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4644.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (177,'Divine Sunderer',2733,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6632.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (178,'Duskblade of Draktharr',3652,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6691.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (179,'Eclipse',3057,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6692.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (180,'Evenshroud',2207,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3001.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (181,'Everfrost',3563,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6656.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (182,'Frostfire Gauntlet',2683,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6662.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (183,'Galeforce',3400,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6671.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (184,'Goredrinker',3576,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6630.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (185,'Hextech Rocketbelt',3211,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3152.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (186,'Immortal Shieldbow',3425,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6673.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (187,'Imperial Mandate',2437,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4005.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (188,'Kraken Slayer',3700,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6672.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (189,'Liandry\'s Anguish',3113,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6653.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (190,'Locket of the Iron Solari',2207,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3190.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (191,'Luden\'s Tempest',3300,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6655.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (192,'Moonstone Renewer',2437,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6617.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (193,'Night Harvester',3424,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4636.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (194,'Prowler\'s Claw',3652,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6693.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (195,'Riftmaker',3000,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/4633.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (196,'Shurelya\'s Battlesong',2437,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/2065.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (197,'Stridebreaker',3583,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6631.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (198,'Sunfire Aegis',3063,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3068.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (199,'Trinity Force',3308,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/3078.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (200,'Turbo Chemtank',2683,'https://static.u.gg/assets/lol/riot_static/12.21.1/img/item/6664.png');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (201,'Bloodward',4254,'https://static.u.gg/assets/lol/ornn_items/7008.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (202,'Caesura',4678,'https://static.u.gg/assets/lol/ornn_items/7024.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (203,'Ceaseless Hunger',4793,'https://static.u.gg/assets/lol/ornn_items/7015.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (204,'Deicide',3967,'https://static.u.gg/assets/lol/ornn_items/7017.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (205,'Draktharr\'s Shadowcarver',4763,'https://static.u.gg/assets/lol/ornn_items/7002.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (206,'Dreamshatter',4583,'https://static.u.gg/assets/lol/ornn_items/7016.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (207,'Equinox',3253,'https://static.u.gg/assets/lol/ornn_items/7023.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (208,'Eternal Winter',4678,'https://static.u.gg/assets/lol/ornn_items/7014.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (209,'Eye of Luden',4273,'https://static.u.gg/assets/lol/ornn_items/7013.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (210,'Forgefire Crest',4167,'https://static.u.gg/assets/lol/ornn_items/7004.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (211,'Icathia\'s Curse',4008,'https://static.u.gg/assets/lol/ornn_items/7009.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (212,'Infinity Force',4308,'https://static.u.gg/assets/lol/ornn_items/7018.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (213,'Liandry\'s Lament',4179,'https://static.u.gg/assets/lol/ornn_items/7012.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (214,'Reliquary of the Golden Dawn',3253,'https://static.u.gg/assets/lol/ornn_items/7019.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (215,'Rimeforged Grasp',3787,'https://static.u.gg/assets/lol/ornn_items/7005.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (216,'Sandshrike\'s Claw',4763,'https://static.u.gg/assets/lol/ornn_items/7000.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (217,'Seat of Command',3989,'https://static.u.gg/assets/lol/ornn_items/7022.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (218,'Shurelya\'s Requiem',3989,'https://static.u.gg/assets/lol/ornn_items/7020.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (219,'Starcaster',3989,'https://static.u.gg/assets/lol/ornn_items/7021.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (220,'Syzygy',4249,'https://static.u.gg/assets/lol/ornn_items/7001.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (221,'Turbocharged Hexperiment',3787,'https://static.u.gg/assets/lol/ornn_items/7003.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (222,'Typhoon',4475,'https://static.u.gg/assets/lol/ornn_items/7006.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (223,'Upgraded Aeropack',4388,'https://static.u.gg/assets/lol/ornn_items/7011.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (224,'Vespertide',4477,'https://static.u.gg/assets/lol/ornn_items/7010.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (225,'Wyrmfallen Sacrifice',4775,'https://static.u.gg/assets/lol/ornn_items/7007.webp');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (226,'Iceborn Gauntlet',3000,'https://static.wikia.nocookie.net/leagueoflegends/images/c/c4/Iceborn_Gauntlet_item.png/revision/latest/scale-to-width-down/40?cb=20221020145819');
INSERT INTO `items` (`id_item`,`item`,`gold`,`imagen`) VALUES (227,'Broken Stopwatch',0,'https://static.wikia.nocookie.net/leagueoflegends/images/8/84/Broken_Stopwatch_item.png/revision/latest/scale-to-width-down/40?cb=20201027193619');
